spring:
  application:
    name: taskTrackerBackend
  datasource:
    password: PASTE_YOUR_DB_PASSWORD
    username: PASTE_YOUR_DB_USERNAME
    url: PASTE_YOUR_DB_URL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update